Update Message definition
load1n9/openai pull request #5
Opened 2023-04-18 04:05 UTC by ferdousbhai

The message type can only have 3 possible roles: "system" | "assistant" | "user".
Messages can contain an optional name field. This is helpful in some applications, here's an example from OpenAI: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb.

2023-04-18 16:40 UTC, lino-levan commented
Seems like this got added pretty recent. LGTM.

2023-04-18 16:41 UTC, lino-levan commented
@ferdousbhai please `deno fmt`.

2023-04-18 19:26 UTC, lino-levan commented
@load1n9 please publish a new version after this gets merged

2023-04-19 02:55 UTC, lino-levan requested changes
Super minor, but could you revert changes to `.gitignore`? Otherwise this looks great, thanks for the contribution!

2023-04-19 05:07 UTC, ferdousbhai commented
Sure, sorry, my first pull request. 😅

2023-04-19 14:17 UTC, merged